service: machete-backend
custom:
  machete_bucket: rippedvines-2-0
package:
  individually: true
provider:
  name: aws
  runtime: nodejs4.3
  profile: personal-account-admin
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'iot:DescribeEndpoint'
        - 'iot:Publish'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 's3:PutObject'
      Resource: "arn:aws:s3:::${self:custom.machete_bucket}/*"
  environment:
    IOT_ROLE: machete-iot-1
    IOT_ENDPOINT: a31p550in0aqjb.iot.us-east-1.amazonaws.com
    MACHETE_BUCKET: ${self:custom.machete_bucket}

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: GET
          cors: true
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: POST
          cors: true
  ripVine:
    handler: handler.ripVine
    timeout: 15
    events:
      - iot:
          sql: "SELECT * FROM '/machete/vine/#'"
    package:
      include:
        - functions/ripVine/ffmpeg
        - functions/ripVine/lame
        - functions/ripVine/ffprobe # see if this binary and those that follow can be excluded
        - functions/ripVine/ffserver
        - functions/ripVine/x264
resources:
  Resources:
    MacheteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.machete_bucket}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods: [GET]
              AllowedOrigins: ['http://machete-site.s3-website-us-east-1.amazonaws.com']
    MacheteBucketPolicy: # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html#cfn-s3-bucketpolicy-policydocument
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.machete_bucket}
        PolicyDocument:
          Statement:
            - Action:
                - "s3:GetObject"
              Effect: "Allow"
              Principal: "*"
              Resource: "arn:aws:s3:::${self:custom.machete_bucket}/*"
              Condition:
                StringLike:
                  aws:Referer:
                    - "http://machete-site.s3-website-us-east-1.amazonaws.com/*"
