service: machete-backend
custom:
  machete_bucket: rippedvines-2-0
package:
  individually: true
provider:
  name: aws
  runtime: nodejs4.3
  profile: personal-account-admin
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'iot:DescribeEndpoint'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"
  environment:
    IOT_ROLE: machete-iot-1
    MACHETE_BUCKET: ${self:custom.machete_bucket}

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: GET
          cors: true
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: POST
          cors: true
  ripVine:
    handler: handler.ripVine
    events:
      - iot:
          sql: "SELECT * FROM '/machete/#'"
    package:
      include:
        - functions/ripVine/ffmpeg
        - functions/ripVine/lame
        - functions/ripVine/ffprobe # see if this binary and those that follow can be excluded
        - functions/ripVine/ffserver
        - functions/ripVine/x264
resources:
  Resources:
    MacheteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.machete_bucket}
